// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtGL3fZFUUYFWmhmooWN6ZQja_9Xpkjg',
    appId: '1:539638376002:web:6e79e8a3d1e82168906fdb',
    messagingSenderId: '539638376002',
    projectId: 'camplink-8e8f1',
    authDomain: 'camplink-8e8f1.firebaseapp.com',
    storageBucket: 'camplink-8e8f1.firebasestorage.app',
    measurementId: 'G-X4KXTJGF60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRBHBkRpLKmsjXSydTUPtdvKrPoLfuQk0',
    appId: '1:539638376002:android:4d5e43d86a5bed3d906fdb',
    messagingSenderId: '539638376002',
    projectId: 'camplink-8e8f1',
    storageBucket: 'camplink-8e8f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3m_wM46jpgPVqWl2MjRMHntQxvnAlJM',
    appId: '1:539638376002:ios:2d8f2fb216a27061906fdb',
    messagingSenderId: '539638376002',
    projectId: 'camplink-8e8f1',
    storageBucket: 'camplink-8e8f1.firebasestorage.app',
    iosBundleId: 'com.kytriq.camplink.camplink',
  );
}
